# ./frontend/Dockerfile

FROM nginx:alpine

# Supprime la config par défaut
RUN rm /etc/nginx/conf.d/default.conf

# 1. Copie ta config Nginx (ça, c'est bon)
# (Il cherche nginx.conf au même niveau que ce Dockerfile)
COPY nginx.conf /etc/nginx/conf.d/

# 2. Copie le CONTENU de ton dossier 'src'
# dans la racine web de Nginx.
# Le "." après "src/" est important !
COPY src/. /usr/share/nginx/html/