services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    networks:
      - app-net
      - admin_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=admin_proxy"
      
      # Middleware : Redirection HTTP -> HTTPS
      - "traefik.http.middlewares.${USERNAME}-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.${USERNAME}-redirect.redirectscheme.permanent=true"

      # Router HTTP (Redirection)
      - "traefik.http.routers.${USERNAME}-front-http.rule=Host(`env-${USERNAME}.iris.a3n.fr`)"
      - "traefik.http.routers.${USERNAME}-front-http.entrypoints=web"
      - "traefik.http.routers.${USERNAME}-front-http.middlewares=${USERNAME}-redirect"

      # Router HTTPS (Principal)
      - "traefik.http.routers.${USERNAME}-front.rule=Host(`env-${USERNAME}.iris.a3n.fr`)"
      - "traefik.http.routers.${USERNAME}-front.entrypoints=websecure"
      - "traefik.http.routers.${USERNAME}-front.tls=true"
      - "traefik.http.routers.${USERNAME}-front.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${USERNAME}-front.service=${USERNAME}-front-svc"

      # Service
      - "traefik.http.services.${USERNAME}-front-svc.loadbalancer.server.port=80"

  backend:
    build: ./backend
    restart: unless-stopped
    networks:
      - app-net

  db:
    image: mariadb:11.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mediaschooldb
      MYSQL_USER: mediaschooluser
      MYSQL_PASSWORD: mediaschoolpass
    networks:
      - app-net

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
    networks:
      - app-net
      - admin_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=admin_proxy"

      # Router HTTPS pour PMA
      - "traefik.http.routers.${USERNAME}-pma.rule=Host(`pma-env-${USERNAME}.iris.a3n.fr`)"
      - "traefik.http.routers.${USERNAME}-pma.entrypoints=websecure"
      - "traefik.http.routers.${USERNAME}-pma.tls=true"
      - "traefik.http.routers.${USERNAME}-pma.tls.certresolver=letsencrypt"
      - "traefik.http.services.${USERNAME}-pma-svc.loadbalancer.server.port=80"

networks:
  app-net:
  admin_proxy:
    external: true